### ISSUE TITLE
Show help if no command is passed

### ISSUE THREAD

**Issue by BrainMaestro** [BrainMaestro/tldr-php#9]
if `tldr` is run without a command to look up, show the help instead of an error message

**Comment by owenvoke** [comment]
I was thinking about this. As you're using Symfony Console, would the default command be good enough? Or do you want a custom help guide?

**Comment by BrainMaestro** [comment]
Default might be good, but a custom guide would be better. Look at https://github.com/k3mist/tldr

**Comment by owenvoke** [comment]
Cool. I'll have a look.
